apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit727
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sit727
  template:
    metadata:
      labels:
        type: deployment
        app: sit727
    spec:
      containers:
      - image: postgres:10
        imagePullPolicy: IfNotPresent
        name: sit727
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: sit727-config
        volumeMounts:
          - name: sit727mnt
            mountPath: /var/lib/postgresql/data
            subPath: sit727/data
      volumes:
      - name: sit727mnt
        persistentVolumeClaim:
          claimName: nfs
      - name: sit727-conf-files-config-mnt
        configMap:
          name: sit727-conf-files-config
      initContainers:
      - name: init-sit727
        image: busybox:1.28
        command: ['sh', '-c', ' cp /var/lib/postgresql/data/postgresql.main.conf /var/lib/postgresql/data/postgresql.conf && cp /var/lib/postgresql/data/pg_hba.main.conf /var/lib/postgresql/data/pg_hba.conf && chmod 600 /var/lib/postgresql/data/postgresql.conf && chmod 600 /var/lib/postgresql/data/pg_hba.conf']
        volumeMounts:
        - name: sit727mnt
          mountPath: /var/lib/postgresql/data
          subPath: sit727/data
        - name: sit727-conf-files-config-mnt
          mountPath: /var/lib/postgresql/data/postgresql.main.conf
          subPath: postgresql.conf
        - name: sit727-conf-files-config-mnt
          mountPath: /var/lib/postgresql/data/pg_hba.main.conf
          subPath: pg_hba.conf            
